---
title: "git_01"
author: "Math_116"
date: "Fall semester"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with commits
Our project will be done using a sequence of save and commits.

## First Verse 
<Put the first two verses of Jabberwocky by Lewis Carrol in this section>
Beware the Jabberwock my son
The jaws that bite the claws that catch
Beware the Jubjub bird and shun
The frumious Bandersnatch


## Second Verse
<Put the first two verses of The Road Not Taken by Robert Frost here>
Two roads diverged in a yellow wood,
And sorry I could not travel both
And be one traveler, long I stood
And looked down one as far as I could
To where it bent in the undergrowth;

Then took the other, as just as fair,
And having perhaps the better claim,
Because it was grassy and wanted wear;
Though as for that the passing there
Had worn them really about the same,

## Third Verse
<Put the first two verses of The Walrus and the Carpenter here>
The sun was shining on the sea
 Shining with all his might
 He did his very best to make
 The billows smooth and bright
 And this was odd because it was
 The middle of the night


 The moon was shining sulkily
 Because she thought the sun
 Had got no business to be there
 After the day was done
 Its very rude of him she said
 To come and spoil the fun


## Last Verse
<Put a short poem of your choice 8-20 lines,here>
If I can stop one heart from breaking
 I shall not live in vain
If I can ease one life the aching
 Or cool one pain
Or help one fainting robin
 Unto his nest again
I shall not live in vain

 Beautiful short poem from a very famous writer

Hans Christian Anderson

To move to breathe to fly to float
To gain all while you give
To roam the roads of lands remote
To travel is to live